# Generated by Django 3.2.4 on 2021-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.IntegerField(default=0, verbose_name='그룹 id')),
                ('title', models.CharField(default='', max_length=128)),
                ('content', models.TextField(default='')),
            ],
            options={
                'verbose_name': '테스트',
                'db_table': 'test_table',
            },
        ),
    ]
